# Generated by Django 4.2.7 on 2024-08-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocalfryapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company_website',
        ),
    ]
